### PR TITLE
tests using express 4

### PR DESCRIPTION
**Pull request by tjmehta**

### CODE REVIEW

**Comment by bkendall** [comment]
:+1:

**Comment by bkendall** [comment]
would you consider:
- adding `- "0.12"` to `.travis.yml` to test against newer node?
- adding `sudo: false` to `.travis.yml` to use containers? (faster tests)

**Comment by bkendall** [comment]
eh - I just make a PR for you ;) #20

**Comment by tjmehta** [comment]
thanks :)


—
@tjmehta

**Pull request merged**
